---


- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt: 
      only_upgrade: yes
      update_cache: yes

- hosts: web_servers
  become: true
  vars:
    apache_package: apache2
    php_package: libapache2-mod-php

  tasks:

  - name: update repository index
    tags: apache, apache2
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
    when: ansible_distribution == "Ubuntu"

